### ISSUE TITLE
brunch watch not working

### ISSUE THREAD

**Issue by ceremcem** [stephenhutchings/jade-static-brunch#3]
`brunch watch` does not compile jade templates except for the first time. When I made a change, I manually stop and start the `brunch watch` command, or simply use `brunch build` command. This is time consuming.

**Comment by ceremcem** [comment]
Seems fixed by https://github.com/stephenhutchings/jade-static-brunch/pull/1

**Comment by stephenhutchings** [comment]
Let me know the status of this now that #1 is merged.

**Comment by ceremcem** [comment]
I'm quite sure that this fixed the problem.
