### ISSUE TITLE
Error while finding jade runtime

### ISSUE THREAD

**Issue by ceremcem** [stephenhutchings/jade-static-brunch#7]
Today I recompiled my project after a long while and I got the following error: 

```
Reading { [Error: ENOENT: no such file or directory, open 'node_modules/jade-static-brunch/node_modules/jade/runtime.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/jade-static-brunch/node_modules/jade/runtime.js' }
```

According to [this](https://github.com/brunch/brunch/issues/1257#issuecomment-200535264) comment, this is because of npm's new module layout handling.

**Comment by stephenhutchings** [comment]
@ceremcem Thanks for this pull request. I've opted simply to remove the runtime as it isn't needed for static compilation.

**Comment by ceremcem** [comment]
You welcome...
